name: Bash Linter
on:
  - push
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 2 # arguments to shfmt.
        with:
          sh_checker_shellcheck_disable: true
          sh_checker_exclude: "flux_log_tmux.sh find_best_server.sh"
